<?xml version="1.0" encoding="utf-8"?><Database Name="Tea_Estates" Class="Tea_Estate_ModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=Tea_Estates;Persist Security Info=True;User ID=sa" SettingsObjectName="WindowsFormsApp1.Properties.Settings" SettingsPropertyName="Tea_EstatesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="Address_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="From_Table" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line_One" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line_Two" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line_Three" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line_Four" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line_Five" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Line_Six" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rest_Of_The_Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postal_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Agreement_Gov" Member="Agreement_Govs">
    <Type Name="Agreement_Gov">
      <Column Name="Agreement_No" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gazzate_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Type_Of_Agreement" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Document_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Agreement_Lease" Member="Agreement_Leases">
    <Type Name="Agreement_Lease">
      <Column Name="Agreement_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Leaser_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Property_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estate_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Start_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="End_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Duration" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Agreement_Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Changes_To_The_Base_Tables" Member="Changes_To_The_Base_Tables">
    <Type Name="Changes_To_The_Base_Table">
      <Column Name="Change_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Changed_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Changed_Table" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Previous_Values" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="New_Values" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Document">
      <Column Name="Document_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="From_Table" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Document_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Primary_Key" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Document_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="File_Location" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Backup_Location" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Due_Payments" Member="Due_Payments">
    <Type Name="Due_Payment">
      <Column Name="Due_Payment_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Due_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Property_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estate_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Agreement_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estate_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Due_Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Leaser_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Payout_Status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Estate" Member="Estates">
    <Type Name="Estate">
      <Column Name="Estate_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estate_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lease_Exclusive_Size" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="District_Secratariat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Agreement_GOV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lease" Member="Leases">
    <Type Name="Lease">
      <Column Name="Lease_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Estate_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Property_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type_Of_Lease" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Rental_Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Lease_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Leaser" Member="Leasers">
    <Type Name="Leaser">
      <Column Name="Leaser_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phone_Number_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Address_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Property" Member="Properties">
    <Type Name="Property">
      <Column Name="Property_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estate_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Property_Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Plan_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Valuation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Current_Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[System_User]" Member="System_Users">
    <Type Name="System_User">
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="System_User_Name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Email_Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Valuations" Member="Valuations">
    <Type Name="Valuation">
      <Column Name="Valuation_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Estate_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Property_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Valuation_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Previous_Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Amended_Value" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Document_ID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="System_User_ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Entry_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>