#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tea_Estates")]
	public partial class Tea_Estate_ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public Tea_Estate_ModelDataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.Tea_EstatesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Tea_Estate_ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Tea_Estate_ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Tea_Estate_ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Tea_Estate_ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Address> Addresses
		{
			get
			{
				return this.GetTable<Address>();
			}
		}
		
		public System.Data.Linq.Table<Agreement_Gov> Agreement_Govs
		{
			get
			{
				return this.GetTable<Agreement_Gov>();
			}
		}
		
		public System.Data.Linq.Table<Agreement_Lease> Agreement_Leases
		{
			get
			{
				return this.GetTable<Agreement_Lease>();
			}
		}
		
		public System.Data.Linq.Table<Changes_To_The_Base_Table> Changes_To_The_Base_Tables
		{
			get
			{
				return this.GetTable<Changes_To_The_Base_Table>();
			}
		}
		
		public System.Data.Linq.Table<Document> Documents
		{
			get
			{
				return this.GetTable<Document>();
			}
		}
		
		public System.Data.Linq.Table<Due_Payment> Due_Payments
		{
			get
			{
				return this.GetTable<Due_Payment>();
			}
		}
		
		public System.Data.Linq.Table<Estate> Estates
		{
			get
			{
				return this.GetTable<Estate>();
			}
		}
		
		public System.Data.Linq.Table<Lease> Leases
		{
			get
			{
				return this.GetTable<Lease>();
			}
		}
		
		public System.Data.Linq.Table<Leaser> Leasers
		{
			get
			{
				return this.GetTable<Leaser>();
			}
		}
		
		public System.Data.Linq.Table<Property> Properties
		{
			get
			{
				return this.GetTable<Property>();
			}
		}
		
		public System.Data.Linq.Table<System_User> System_Users
		{
			get
			{
				return this.GetTable<System_User>();
			}
		}
		
		public System.Data.Linq.Table<Valuation> Valuations
		{
			get
			{
				return this.GetTable<Valuation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Address")]
	public partial class Address
	{
		
		private System.Guid _Address_ID;
		
		private string _From_Table;
		
		private string _Origin_Description;
		
		private string _Line_One;
		
		private string _Line_Two;
		
		private string _Line_Three;
		
		private string _Line_Four;
		
		private string _Line_Five;
		
		private string _Line_Six;
		
		private string _Rest_Of_The_Address;
		
		private string _City;
		
		private string _Postal_Code;
		
		private System.Guid _System_User_ID;
		
		public Address()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Table", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string From_Table
		{
			get
			{
				return this._From_Table;
			}
			set
			{
				if ((this._From_Table != value))
				{
					this._From_Table = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origin_Description", DbType="NVarChar(50)")]
		public string Origin_Description
		{
			get
			{
				return this._Origin_Description;
			}
			set
			{
				if ((this._Origin_Description != value))
				{
					this._Origin_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_One", DbType="NVarChar(50)")]
		public string Line_One
		{
			get
			{
				return this._Line_One;
			}
			set
			{
				if ((this._Line_One != value))
				{
					this._Line_One = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_Two", DbType="NVarChar(50)")]
		public string Line_Two
		{
			get
			{
				return this._Line_Two;
			}
			set
			{
				if ((this._Line_Two != value))
				{
					this._Line_Two = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_Three", DbType="NVarChar(50)")]
		public string Line_Three
		{
			get
			{
				return this._Line_Three;
			}
			set
			{
				if ((this._Line_Three != value))
				{
					this._Line_Three = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_Four", DbType="NVarChar(50)")]
		public string Line_Four
		{
			get
			{
				return this._Line_Four;
			}
			set
			{
				if ((this._Line_Four != value))
				{
					this._Line_Four = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_Five", DbType="NVarChar(50)")]
		public string Line_Five
		{
			get
			{
				return this._Line_Five;
			}
			set
			{
				if ((this._Line_Five != value))
				{
					this._Line_Five = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Line_Six", DbType="NVarChar(50)")]
		public string Line_Six
		{
			get
			{
				return this._Line_Six;
			}
			set
			{
				if ((this._Line_Six != value))
				{
					this._Line_Six = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rest_Of_The_Address", DbType="NVarChar(100)")]
		public string Rest_Of_The_Address
		{
			get
			{
				return this._Rest_Of_The_Address;
			}
			set
			{
				if ((this._Rest_Of_The_Address != value))
				{
					this._Rest_Of_The_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postal_Code", DbType="NVarChar(50)")]
		public string Postal_Code
		{
			get
			{
				return this._Postal_Code;
			}
			set
			{
				if ((this._Postal_Code != value))
				{
					this._Postal_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Agreement_Gov")]
	public partial class Agreement_Gov
	{
		
		private string _Agreement_No;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _Gazzate_Date;
		
		private string _Type_Of_Agreement;
		
		private string _Remarks;
		
		private System.Nullable<System.Guid> _Document_ID;
		
		private System.Guid _System_User_ID;
		
		private System.Nullable<System.DateTime> _Entry_Date;
		
		public Agreement_Gov()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agreement_No", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Agreement_No
		{
			get
			{
				return this._Agreement_No;
			}
			set
			{
				if ((this._Agreement_No != value))
				{
					this._Agreement_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gazzate_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Gazzate_Date
		{
			get
			{
				return this._Gazzate_Date;
			}
			set
			{
				if ((this._Gazzate_Date != value))
				{
					this._Gazzate_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Of_Agreement", DbType="NVarChar(50)")]
		public string Type_Of_Agreement
		{
			get
			{
				return this._Type_Of_Agreement;
			}
			set
			{
				if ((this._Type_Of_Agreement != value))
				{
					this._Type_Of_Agreement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(500)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Document_ID
		{
			get
			{
				return this._Document_ID;
			}
			set
			{
				if ((this._Document_ID != value))
				{
					this._Document_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Agreement_Lease")]
	public partial class Agreement_Lease
	{
		
		private string _Agreement_ID;
		
		private System.Guid _Leaser_ID;
		
		private string _Property_ID;
		
		private string _Estate_ID;
		
		private System.Nullable<System.DateTime> _Start_Date;
		
		private System.Nullable<System.DateTime> _End_Date;
		
		private string _Duration;
		
		private System.Nullable<decimal> _Agreement_Value;
		
		private System.Guid _System_User_ID;
		
		private System.Nullable<System.DateTime> _Entry_Date;
		
		public Agreement_Lease()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agreement_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Agreement_ID
		{
			get
			{
				return this._Agreement_ID;
			}
			set
			{
				if ((this._Agreement_ID != value))
				{
					this._Agreement_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leaser_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Leaser_ID
		{
			get
			{
				return this._Leaser_ID;
			}
			set
			{
				if ((this._Leaser_ID != value))
				{
					this._Leaser_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_ID", DbType="NVarChar(50)")]
		public string Property_ID
		{
			get
			{
				return this._Property_ID;
			}
			set
			{
				if ((this._Property_ID != value))
				{
					this._Property_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_ID
		{
			get
			{
				return this._Estate_ID;
			}
			set
			{
				if ((this._Estate_ID != value))
				{
					this._Estate_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Start_Date
		{
			get
			{
				return this._Start_Date;
			}
			set
			{
				if ((this._Start_Date != value))
				{
					this._Start_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> End_Date
		{
			get
			{
				return this._End_Date;
			}
			set
			{
				if ((this._End_Date != value))
				{
					this._End_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duration", DbType="NVarChar(50)")]
		public string Duration
		{
			get
			{
				return this._Duration;
			}
			set
			{
				if ((this._Duration != value))
				{
					this._Duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agreement_Value", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Agreement_Value
		{
			get
			{
				return this._Agreement_Value;
			}
			set
			{
				if ((this._Agreement_Value != value))
				{
					this._Agreement_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Changes_To_The_Base_Tables")]
	public partial class Changes_To_The_Base_Table
	{
		
		private System.Guid _Change_ID;
		
		private System.DateTime _Entry_Date;
		
		private System.Guid _System_User_ID;
		
		private System.Nullable<System.DateTime> _Changed_Date;
		
		private string _Changed_Table;
		
		private string _Previous_Values;
		
		private string _New_Values;
		
		public Changes_To_The_Base_Table()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Change_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Change_ID
		{
			get
			{
				return this._Change_ID;
			}
			set
			{
				if ((this._Change_ID != value))
				{
					this._Change_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Changed_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Changed_Date
		{
			get
			{
				return this._Changed_Date;
			}
			set
			{
				if ((this._Changed_Date != value))
				{
					this._Changed_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Changed_Table", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Changed_Table
		{
			get
			{
				return this._Changed_Table;
			}
			set
			{
				if ((this._Changed_Table != value))
				{
					this._Changed_Table = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previous_Values", DbType="NVarChar(1000)")]
		public string Previous_Values
		{
			get
			{
				return this._Previous_Values;
			}
			set
			{
				if ((this._Previous_Values != value))
				{
					this._Previous_Values = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_New_Values", DbType="NVarChar(1000)")]
		public string New_Values
		{
			get
			{
				return this._New_Values;
			}
			set
			{
				if ((this._New_Values != value))
				{
					this._New_Values = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Documents")]
	public partial class Document
	{
		
		private System.Guid _Document_ID;
		
		private string _From_Table;
		
		private string _Document_Type;
		
		private string _Primary_Key;
		
		private string _Document_Name;
		
		private string _File_Location;
		
		private string _Backup_Location;
		
		private string _Remarks;
		
		private System.Guid _System_User_ID;
		
		private System.Nullable<System.DateTime> _Entry_Date;
		
		public Document()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Document_ID
		{
			get
			{
				return this._Document_ID;
			}
			set
			{
				if ((this._Document_ID != value))
				{
					this._Document_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Table", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string From_Table
		{
			get
			{
				return this._From_Table;
			}
			set
			{
				if ((this._From_Table != value))
				{
					this._From_Table = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_Type", DbType="NVarChar(50)")]
		public string Document_Type
		{
			get
			{
				return this._Document_Type;
			}
			set
			{
				if ((this._Document_Type != value))
				{
					this._Document_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Key", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Primary_Key
		{
			get
			{
				return this._Primary_Key;
			}
			set
			{
				if ((this._Primary_Key != value))
				{
					this._Primary_Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_Name", DbType="NVarChar(50)")]
		public string Document_Name
		{
			get
			{
				return this._Document_Name;
			}
			set
			{
				if ((this._Document_Name != value))
				{
					this._Document_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_File_Location", DbType="NVarChar(200)")]
		public string File_Location
		{
			get
			{
				return this._File_Location;
			}
			set
			{
				if ((this._File_Location != value))
				{
					this._File_Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Backup_Location", DbType="NVarChar(200)")]
		public string Backup_Location
		{
			get
			{
				return this._Backup_Location;
			}
			set
			{
				if ((this._Backup_Location != value))
				{
					this._Backup_Location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(500)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Due_Payments")]
	public partial class Due_Payment
	{
		
		private System.Guid _Due_Payment_ID;
		
		private System.DateTime _Due_Date;
		
		private string _Property_ID;
		
		private string _Estate_ID;
		
		private string _Agreement_ID;
		
		private string _Estate_Name;
		
		private System.Nullable<decimal> _Due_Value;
		
		private System.Guid _Leaser_ID;
		
		private string _Payout_Status;
		
		private System.DateTime _Entry_Date;
		
		private System.Guid _System_User_ID;
		
		public Due_Payment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Due_Payment_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Due_Payment_ID
		{
			get
			{
				return this._Due_Payment_ID;
			}
			set
			{
				if ((this._Due_Payment_ID != value))
				{
					this._Due_Payment_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Due_Date", DbType="Date NOT NULL")]
		public System.DateTime Due_Date
		{
			get
			{
				return this._Due_Date;
			}
			set
			{
				if ((this._Due_Date != value))
				{
					this._Due_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_ID", DbType="NVarChar(50)")]
		public string Property_ID
		{
			get
			{
				return this._Property_ID;
			}
			set
			{
				if ((this._Property_ID != value))
				{
					this._Property_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_ID
		{
			get
			{
				return this._Estate_ID;
			}
			set
			{
				if ((this._Estate_ID != value))
				{
					this._Estate_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agreement_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Agreement_ID
		{
			get
			{
				return this._Agreement_ID;
			}
			set
			{
				if ((this._Agreement_ID != value))
				{
					this._Agreement_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_Name
		{
			get
			{
				return this._Estate_Name;
			}
			set
			{
				if ((this._Estate_Name != value))
				{
					this._Estate_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Due_Value", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Due_Value
		{
			get
			{
				return this._Due_Value;
			}
			set
			{
				if ((this._Due_Value != value))
				{
					this._Due_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leaser_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Leaser_ID
		{
			get
			{
				return this._Leaser_ID;
			}
			set
			{
				if ((this._Leaser_ID != value))
				{
					this._Leaser_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payout_Status", DbType="NVarChar(50)")]
		public string Payout_Status
		{
			get
			{
				return this._Payout_Status;
			}
			set
			{
				if ((this._Payout_Status != value))
				{
					this._Payout_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estate")]
	public partial class Estate
	{
		
		private string _Estate_ID;
		
		private string _Estate_Name;
		
		private string _Size;
		
		private string _Lease_Exclusive_Size;
		
		private string _District;
		
		private string _District_Secratariat;
		
		private string _Agreement_GOV;
		
		private System.Nullable<System.Guid> _Address_ID;
		
		private System.Guid _System_User_ID;
		
		private System.Nullable<System.DateTime> _Entry_Date;
		
		public Estate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_ID
		{
			get
			{
				return this._Estate_ID;
			}
			set
			{
				if ((this._Estate_ID != value))
				{
					this._Estate_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_Name
		{
			get
			{
				return this._Estate_Name;
			}
			set
			{
				if ((this._Estate_Name != value))
				{
					this._Estate_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(50)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lease_Exclusive_Size", DbType="NVarChar(50)")]
		public string Lease_Exclusive_Size
		{
			get
			{
				return this._Lease_Exclusive_Size;
			}
			set
			{
				if ((this._Lease_Exclusive_Size != value))
				{
					this._Lease_Exclusive_Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(50)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this._District = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District_Secratariat", DbType="NVarChar(50)")]
		public string District_Secratariat
		{
			get
			{
				return this._District_Secratariat;
			}
			set
			{
				if ((this._District_Secratariat != value))
				{
					this._District_Secratariat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agreement_GOV", DbType="NVarChar(50)")]
		public string Agreement_GOV
		{
			get
			{
				return this._Agreement_GOV;
			}
			set
			{
				if ((this._Agreement_GOV != value))
				{
					this._Agreement_GOV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lease")]
	public partial class Lease
	{
		
		private System.Guid _Lease_ID;
		
		private string _Estate_ID;
		
		private string _Property_ID;
		
		private string _Type_Of_Lease;
		
		private System.Nullable<decimal> _Rental_Value;
		
		private System.Nullable<bool> _Lease_Status;
		
		private System.Guid _System_User_ID;
		
		private System.DateTime _Entry_Date;
		
		public Lease()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lease_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Lease_ID
		{
			get
			{
				return this._Lease_ID;
			}
			set
			{
				if ((this._Lease_ID != value))
				{
					this._Lease_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_ID
		{
			get
			{
				return this._Estate_ID;
			}
			set
			{
				if ((this._Estate_ID != value))
				{
					this._Estate_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_ID", DbType="NVarChar(50)")]
		public string Property_ID
		{
			get
			{
				return this._Property_ID;
			}
			set
			{
				if ((this._Property_ID != value))
				{
					this._Property_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Of_Lease", DbType="NVarChar(50)")]
		public string Type_Of_Lease
		{
			get
			{
				return this._Type_Of_Lease;
			}
			set
			{
				if ((this._Type_Of_Lease != value))
				{
					this._Type_Of_Lease = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rental_Value", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Rental_Value
		{
			get
			{
				return this._Rental_Value;
			}
			set
			{
				if ((this._Rental_Value != value))
				{
					this._Rental_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lease_Status", DbType="Bit")]
		public System.Nullable<bool> Lease_Status
		{
			get
			{
				return this._Lease_Status;
			}
			set
			{
				if ((this._Lease_Status != value))
				{
					this._Lease_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leaser")]
	public partial class Leaser
	{
		
		private System.Guid _Leaser_ID;
		
		private string _Name;
		
		private System.Nullable<System.Guid> _Phone_Number_ID;
		
		private string _Email;
		
		private System.Nullable<System.Guid> _Address_ID;
		
		private System.Guid _System_User_ID;
		
		private System.Nullable<System.DateTime> _Entry_Date;
		
		public Leaser()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leaser_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Leaser_ID
		{
			get
			{
				return this._Leaser_ID;
			}
			set
			{
				if ((this._Leaser_ID != value))
				{
					this._Leaser_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone_Number_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Phone_Number_ID
		{
			get
			{
				return this._Phone_Number_ID;
			}
			set
			{
				if ((this._Phone_Number_ID != value))
				{
					this._Phone_Number_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Property")]
	public partial class Property
	{
		
		private string _Property_ID;
		
		private string _Estate_ID;
		
		private string _Property_Type;
		
		private string _Size;
		
		private string _Plan_Number;
		
		private string _Valuation;
		
		private System.Nullable<decimal> _Current_Value;
		
		private System.Guid _System_User_ID;
		
		private System.Nullable<System.DateTime> _Entry_Date;
		
		public Property()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Property_ID
		{
			get
			{
				return this._Property_ID;
			}
			set
			{
				if ((this._Property_ID != value))
				{
					this._Property_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_ID
		{
			get
			{
				return this._Estate_ID;
			}
			set
			{
				if ((this._Estate_ID != value))
				{
					this._Estate_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_Type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Property_Type
		{
			get
			{
				return this._Property_Type;
			}
			set
			{
				if ((this._Property_Type != value))
				{
					this._Property_Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="NVarChar(50)")]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this._Size = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plan_Number", DbType="NVarChar(50)")]
		public string Plan_Number
		{
			get
			{
				return this._Plan_Number;
			}
			set
			{
				if ((this._Plan_Number != value))
				{
					this._Plan_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuation", DbType="NVarChar(50)")]
		public string Valuation
		{
			get
			{
				return this._Valuation;
			}
			set
			{
				if ((this._Valuation != value))
				{
					this._Valuation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_Value", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Current_Value
		{
			get
			{
				return this._Current_Value;
			}
			set
			{
				if ((this._Current_Value != value))
				{
					this._Current_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[System_User]")]
	public partial class System_User
	{
		
		private System.Guid _System_User_ID;
		
		private string _System_User_Name;
		
		private string _Password;
		
		private System.Nullable<System.Guid> _Address_ID;
		
		private string _Email_Address;
		
		private string _Full_Name;
		
		private System.Nullable<System.DateTime> _Entry_Date;
		
		public System_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_Name", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string System_User_Name
		{
			get
			{
				return this._System_User_Name;
			}
			set
			{
				if ((this._System_User_Name != value))
				{
					this._System_User_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Address_ID
		{
			get
			{
				return this._Address_ID;
			}
			set
			{
				if ((this._Address_ID != value))
				{
					this._Address_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_Address", DbType="NVarChar(200)")]
		public string Email_Address
		{
			get
			{
				return this._Email_Address;
			}
			set
			{
				if ((this._Email_Address != value))
				{
					this._Email_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="NVarChar(200)")]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this._Full_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Valuations")]
	public partial class Valuation
	{
		
		private System.Guid _Valuation_ID;
		
		private string _Estate_ID;
		
		private string _Property_ID;
		
		private System.Nullable<System.DateTime> _Valuation_Date;
		
		private System.Nullable<decimal> _Previous_Value;
		
		private System.Nullable<decimal> _Amended_Value;
		
		private string _Remarks;
		
		private System.Nullable<System.Guid> _Document_ID;
		
		private System.Guid _System_User_ID;
		
		private System.DateTime _Entry_Date;
		
		public Valuation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuation_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Valuation_ID
		{
			get
			{
				return this._Valuation_ID;
			}
			set
			{
				if ((this._Valuation_ID != value))
				{
					this._Valuation_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estate_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Estate_ID
		{
			get
			{
				return this._Estate_ID;
			}
			set
			{
				if ((this._Estate_ID != value))
				{
					this._Estate_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Property_ID", DbType="NVarChar(50)")]
		public string Property_ID
		{
			get
			{
				return this._Property_ID;
			}
			set
			{
				if ((this._Property_ID != value))
				{
					this._Property_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valuation_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Valuation_Date
		{
			get
			{
				return this._Valuation_Date;
			}
			set
			{
				if ((this._Valuation_Date != value))
				{
					this._Valuation_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Previous_Value", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Previous_Value
		{
			get
			{
				return this._Previous_Value;
			}
			set
			{
				if ((this._Previous_Value != value))
				{
					this._Previous_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amended_Value", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Amended_Value
		{
			get
			{
				return this._Amended_Value;
			}
			set
			{
				if ((this._Amended_Value != value))
				{
					this._Amended_Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(500)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Document_ID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Document_ID
		{
			get
			{
				return this._Document_ID;
			}
			set
			{
				if ((this._Document_ID != value))
				{
					this._Document_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System_User_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid System_User_ID
		{
			get
			{
				return this._System_User_ID;
			}
			set
			{
				if ((this._System_User_ID != value))
				{
					this._System_User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entry_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Entry_Date
		{
			get
			{
				return this._Entry_Date;
			}
			set
			{
				if ((this._Entry_Date != value))
				{
					this._Entry_Date = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
